export const LOCAL_STORAGE_KEYS = {
  COMPANY_BIO: "companyBio",
  JOB_DESCRIPTION: "jobDescription",
  COVER_LETTER_THREAD_ID: "coverLetterThreadId",
  RESUME_THREAD_ID: "resumeThreadId",
  COVER_LETTER_LATEX_CONTENT: "coverLetterLatexContent",
  RESUME_LATEX_CONTENT: "resumeLatexContent",
  MODEL_NAME: "modelName",
  MODEL_API_KEYS: "modelApiKeys",
  MAIL_EDITOR_STORAGE_KEY: "mail-editor-content",
  MAIL_EDITOR_SCROLL_KEY: "mail-editor-scroll-position",
  COVER_LETTER_CONTEXT: "coverLetterContext",
  HUMANIZE_PRO_FOR_COVER_LETTER: "humanizeProForCoverLetter",
  HUMANIZE_PRO_FOR_RESUME: "humanizeProForResume",
};
