export const site = {
  name: "Tweakleaf",
  description:
    "Tweak your LaTeX resume and cover-letter with ai agents for free.",
  logo: "/logo.png",
  url: "https://tweakleaf.com",
  ogImage: "https://tweakleaf.com/opengraph-image.png",
  links: {
    github: "https://github.com/tweakleaf",
    linkedin: "https://www.linkedin.com/company/tweakleaf",
    instagram: "https://www.instagram.com/tweakleaf",
    facebook: "https://www.facebook.com/tweakleaf",
    youtube: "https://www.youtube.com/tweakleaf",
    tiktok: "https://www.tiktok.com/@tweakleaf",
    reddit: "https://www.reddit.com/r/tweakleaf",
    telegram: "https://t.me/tweakleaf",
    x: "https://x.com/tweakleaf",
  },
  tags: ["job", "job-search", "job-application", "job-board", "job-posting"],
  keywords: [
    "job",
    "job-search",
    "job-application",
    "job-board",
    "job-posting",
  ],
  author: "Tweakleaf",
  creator: "Tweakleaf",
  publisher: "Tweakleaf",
  robots: "index, follow",
  google: {
    analytics: "G-XXXXXXXXXX",
    searchConsole: "XXXXXXXXXX",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://tweakleaf.com",
    siteName: "Tweakleaf",
    title: "Tweakleaf",
    description:
      "Tweakleaf is a platform for job seekers to find jobs and apply to them.",
    image: "https://tweakleaf.com/opengraph-image.png",
  },
  header: {
    headerOne: "Apply 100+ jobs in time of 2 with just $0.5 with optimization",
    headerTwo: "You career is worth more than $0.1",
    headerThree: "Why only to apply only 10 companies a day ?",
    headerFour: "Tweak.Apply",
    headerFive: "Tweak.Apply",
    headerSix: "Tweak.Apply",
    headerSeven: "Tweak.Apply",
  },
  pricingPage: {
    title: "Pricing",
    headerOne: "Simple, Transparent Pricing",
    headertwo:
      "Choose the perfect plan for your job search needs. All plans include access to our AI-powered resume tweaking and job matching features.",
  },
  aboutPage: {
    title: "About",
    headerOne: "About",
    headertwo: "About",
    headerThree: "About",
    headerFour: "About",
    headerFive: "About",
    headerSix: "About",
  },
  notifications: "Tweak is under development, will be live sooooon ! 🎉",
};
