export const site = {
  name: "Tweak",
  description:
    "Tweak.Apply is a platform for job seekers to find jobs and apply to them.",
  url: "https://tweak.Apply.com",
  ogImage: "https://tweak.Apply.com/og-image.png",
  links: {
    twitter: "https://x.com/tweak.Apply",
    github: "https://github.com/tweak.Apply",
    linkedin: "https://www.linkedin.com/company/tweak.Apply",
    instagram: "https://www.instagram.com/tweak.Apply",
    facebook: "https://www.facebook.com/tweak.Apply",
    youtube: "https://www.youtube.com/tweak.Apply",
    tiktok: "https://www.tiktok.com/@tweak.Apply",
    reddit: "https://www.reddit.com/r/tweak.Apply",
    telegram: "https://t.me/tweak.Apply",
    x: "https://x.com/tweak.Apply",
  },
  tags: ["job", "job-search", "job-application", "job-board", "job-posting"],
  keywords: [
    "job",
    "job-search",
    "job-application",
    "job-board",
    "job-posting",
  ],
  author: "Tweak.Apply",
  creator: "Tweak.Apply",
  publisher: "Tweak.Apply",
  robots: "index, follow",
  google: {
    analytics: "G-XXXXXXXXXX",
    searchConsole: "XXXXXXXXXX",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://tweak.Apply.com",
    siteName: "Tweak.Apply",
    title: "Tweak.Apply",
    description:
      "Tweak.Apply is a platform for job seekers to find jobs and apply to them.",
    image: "https://tweak.Apply.com/og-image.png",
  },
  header: {
    headerOne: "Apply 100+ jobs in time of 2 with just $0.5 with optimization",
    headerTwo: "You career is worth more than $0.1",
    headerThree: "Why only to apply only 10 companies a day ?",
    headerFour: "Tweak.Apply",
    headerFive: "Tweak.Apply",
    headerSix: "Tweak.Apply",
    headerSeven: "Tweak.Apply",
  },
  pricingPage: {
    title: "Pricing",
    headerOne: "Simple, Transparent Pricing",
    headertwo:
      "Choose the perfect plan for your job search needs. All plans include access to our AI-powered resume tweaking and job matching features.",
  },
  aboutPage: {
    title: "About",
    headerOne: "About",
    headertwo: "About",
    headerThree: "About",
    headerFour: "About",
    headerFive: "About",
    headerSix: "About",
  },
  notifications: "Tweak is under development, will be live sooooon ! 🎉",
};
